# Generated by Django 6.0.5 on 2026-05-26 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Telefon raqam formatda bo'lishi kerak: '+998901234567'",
                        regex="^\\+?998\\d{9}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
