# Generated by Django 5.2.11 on 2026-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("TEACHER", "Teacher"),
                ],
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
