# Generated by Django 5.2.11 on 2026-06-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("students", "0002_student_tz_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="group_id",
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="groups.group",
            ),
        ),
    ]
